### ISSUE TITLE
Program does not run

### ISSUE THREAD

**Issue by Clinqk** [jac0b-w/album-art-wallpaper#3]
When starting the program form the .exe or shortcuts in the Start Menu, nothing happens.
When checking the errors.log file, this error shows up:

> 2020-10-29 11:30:37,769 main error
> Traceback (most recent call last):
>   File "album-art-wallpaper.py", line 737, in <module>
>   File "album-art-wallpaper.py", line 61, in set_default_wallpaper
> ValueError: max() arg is an empty sequence
> 

Desktop
 - OS: Windows 10 (2004)
 - Version 3.0 (This has been an issue in all previous versions as well)

**Comment by jac0b-w** [comment]
@Clinqk Just released v3.1 hopefully this fixes the issue or at least prevents the exception. I'll leave the issue open for a while please let me know if you still get this error. Thanks :)

**Comment by right-head** [comment]
Hey jac0b I appreciate the work you do.Thank you for the updates.

I was wondering which features added to Album-Art-Wallpaper v.3
Because I like the v.2 and if v.3 didn't add much I'll be glad continuing
to use v.2

Have a nice day

Emre

30 Eki 2020 Cum 05:06 tarihinde Jacob <notifications@github.com> şunu yazdı:

**Comment by jac0b-w** [comment]
@right-head You can see the added features on the [releases page](https://github.com/jac0b-w/album-art-wallpaper/releases) Pretty much bug fixes and a new gradient option for the background have been added.

**Comment by Clinqk** [comment]
The issue has now been solved 👍
